//import {createContext} from "react";

export const GroupKeys = {
    Name: "Name",
    Enchants: "Enchants",
    Gems: "Gems",
    Elixirs: "Elixirs",
    Deaths: "Deaths",
    ProtPotions: "ProtPotions",
    Consumes: "Consumes",
    Abilities: "Abilities",
    Damage: "Damage",
    DispelsInterrupts: "DispelsInterrupts",
}

export const DataPoints = {
    Name: "Name",
    Enchants: "Enchants",
    GemsCommon: "GemsCommon",
    GemsUncommon: "GemUncommon",
    GemsRare: "GemsRare",
    GemsEpic: "GemsEpic",
    GemsList: "GemsList",
    Elixirs: "Elixirs",
    ElixirsFlasks: "ElixirsFlasks",
    ElixirsGuardian: "ElixirsGuardian",
    ElixirsBattle: "ElixirsBattle",
    ElixirsFood: "ElixirsFood",
    ElixirsSeasonal: "ElixirsSeasonal",
    ElixirsScrolls: "ElixirsScrolls",
    ElixirsWeaponEnchants: "ElixirsWeaponEnchants",
    Deaths: "Deaths",
    ProtectionPotionsTotal: "ProtectionPotionsTotal",
    ProtectionPotionsTotalAbsorbed: "ProtectionPotionsTotalAbsorbed",
    ProtectionPotionsNature: "ProtectionPotionsNature",
    ProtectionPotionsGreaterNature: "ProtectionPotionsGreaterNature",
    ProtectionPotionsMajorNature: "ProtectionPotionsMajorNature",
    ProtectionPotionsNatureAbsorbed: "ProtectionPotionsNatureAbsorbed",
    ProtectionPotionsFire: "ProtectionPotionsFire",
    ProtectionPotionsGreaterFire: "ProtectionPotionsGreaterFire",
    ProtectionPotionsMajorFire: "ProtectionPotionsMajorFire",
    ProtectionPotionsFireAbsorbed: "ProtectionPotionsFireAbsorbed",
    ProtectionPotionsFrost: "ProtectionPotionsFrost",
    ProtectionPotionsGreaterFrost: "ProtectionPotionsGreaterFrost",
    ProtectionPotionsMajorFrost: "ProtectionPotionsMajorFrost",
    ProtectionPotionsFrostAbsorbed: "ProtectionPotionsFrostAbsorbed",
    ProtectionPotionsShadow: "ProtectionPotionsShadow",
    ProtectionPotionsGreaterShadow: "ProtectionPotionsGreaterShadow",
    ProtectionPotionsMajorShadow: "ProtectionPotionsMajorShadow",
    ProtectionPotionsShadowAbsorbed: "ProtectionPotionsShadowAbsorbed",
    ProtectionPotionsGreaterArcane: "ProtectionPotionsGreaterArcane",
    ProtectionPotionsMajorArcane: "ProtectionPotionsMajorArcane",
    ProtectionPotionsArcaneAbsorbed: "ProtectionPotionsArcaneAbsorbed",
    ConsumesPotions: "ConsumesPotions",
    ConsumesDrums: "ConsumesDrums",
    ConsumesGems: "ConsumesGems",
    ConsumesExplosives: "ConsumesExplosives",
    ConsumesBandages: "ConsumesBandages",
    ConsumesManaPots: "ConsumesManaPots",
    ConsumesRunes: "ConsumesRunes",
    ConsumesRejuvPots: "ConsumesRejuvPots",
    ConsumesHealthPots: "ConsumesHealthPots",
    ConsumesHealthStones: "ConsumesHealthStones",
    ConsumesWhipperRootTuber: "ConsumesWhipperRootTuber",
    ConsumesRagePotions: "ConsumesRagePotions",
    ConsumesThistleTea: "ConsumesThistleTea",
    ConsumesRestorationPots: "ConsumesRestorationPots",
    ConsumesFreeActionPotion: "ConsumesFreeActionPotion",
    ConsumesManaGem: "ConsumesManaGem",
    ConsumesNightmareSeed: "ConsumesNightmareSeed",
    ConsumesStoneshield: "ConsumesStoneshield",
    ConsumesHeavyRuneclothBandage: "ConsumesHeavyRuneclothBandage",
    ConsumesAntiVenom: "ConsumesAntiVenom",
    ConsumesHolyWater: "ConsumesHolyWater",
    ConsumesSapperCharge: "ConsumesSapperCharge",
    ConsumesEzThro: "ConsumesEzThro",
    ConsumesDenseDynamite: "ConsumesDenseDynamite",
    ConsumesDrumsBattle: "ConsumesDrumsBattle",
    ConsumesDrumsRestoration: "ConsumesDrumsRestoration",
    ConsumesDrumsPanic: "ConsumesDrumsPanic",
    ConsumesDrumsWar: "ConsumesDrumsWar",
    ConsumesInsaneStrength: "ConsumesInsaneStrength",
    ConsumesShrouding: "ConsumesShrouding",
    ConsumesFelRegeneration: "ConsumesFelRegeneration",
    ConsumesHeroic: "ConsumesHeroic",
    ConsumesDestruction: "ConsumesDestruction",
    ConsumesHaste: "ConsumesHaste",
    ConsumesFelMana: "ConsumesFelMana",
    ConsumesIronshield: "ConsumesIronshield",
    DispelTotal: "DispelTotal",
    DispelBoss: "DispelBoss",
    DispelTrash: "DispelTrash",
    DispelPoison: "DispelPoison",
    DispelDisease: "DispelDisease",
    DispelCurse: "DispelCurse",
    DispelMagic: "DispelMagic",
    DispelFrenzy: "DispelFrenzy",
    DispelDruidCurePoison: "DispelDruidCurePoison",
    DispelDruidAbolishPoison: "DispelDruidAbolishPoison",
    DispelDruidRemoveCurse: "DispelDruidRemoveCurse",
    DispelHunterTranqShot: "DispelHunterTranqShot",
    DispelMageRemoveLesserCurse: "DispelMageRemoveLesserCurse",
    DispelPaladinPurify: "DispelPaladinPurify",
    DispelPaladinCleanse: "DispelPaladinCleanse",
    DispelPriestDispelMagic: "DispelPriestDispelMagic",
    DispelPriestCureDisease: "DispelPriestCureDisease",
    DispelPriestAbolishDisease: "DispelPriestAbolishDisease",
    DispelShamanPurge: "DispelShamanPurge",
    DispelShamanCurePoison: "DispelShamanCurePoison",
    DispelShamanCureDisease: "DispelShamanCureDisease",
    DispelShamanPoisonCleansingTotem: "DispelShamanPoisonCleansingTotem",
    DispelShamanDiseaseCleansingTotem: "DispelShamanDiseaseCleansingTotem",
    InterruptTotal: "InterruptTotal",
    InterruptDruidBash: "InterruptDruidBash",
    InterruptDruidFeralCharge: "InterruptDruidFeralCharge",
    InterruptMageCounterspell: "InterruptMageCounterspell",
    InterruptPaladinHammerOfJustice: "InterruptPaladinHammerOfJustice",
    InterruptPriestSilence: "InterruptPriestSilence",
    InterruptRogueKick: "InterruptRogueKick",
    InterruptShamanEarthShock: "InterruptShamanEarthShock",
    InterruptWarriorPummel: "InterruptWarriorPummel",
};

export const emptyData = {
    [DataPoints.Name]: " ",
    [DataPoints.Enchants]: " ",
    [DataPoints.GemsCommon]: " ",
    [DataPoints.GemsUncommon]: " ",
    [DataPoints.GemsRare]: " ",
    [DataPoints.GemsEpic]: " ",
    [DataPoints.GemsList]: [],
    [DataPoints.Elixirs]: " ",
    [DataPoints.ElixirsFlasks]: [],
    [DataPoints.ElixirsGuardian]: [],
    [DataPoints.ElixirsBattle]: [],
    [DataPoints.ElixirsFood]: [],
    [DataPoints.ElixirsSeasonal]: [],
    [DataPoints.ElixirsScrolls]: [],
    [DataPoints.ElixirsWeaponEnchants]: [],
    [DataPoints.Deaths]: " ",
    [DataPoints.ProtectionPotionsTotal]: " ",
    [DataPoints.ProtectionPotionsTotalAbsorbed]: " ",
    [DataPoints.ProtectionPotionsNature]: " ",
    [DataPoints.ProtectionPotionsGreaterNature]: " ",
    [DataPoints.ProtectionPotionsMajorNature]: " ",
    [DataPoints.ProtectionPotionsNatureAbsorbed]: " ",
    [DataPoints.ProtectionPotionsFire]: " ",
    [DataPoints.ProtectionPotionsGreaterFire]: " ",
    [DataPoints.ProtectionPotionsMajorFire]: " ",
    [DataPoints.ProtectionPotionsFireAbsorbed]: " ",
    [DataPoints.ProtectionPotionsFrost]: " ",
    [DataPoints.ProtectionPotionsGreaterFrost]: " ",
    [DataPoints.ProtectionPotionsMajorFrost]: " ",
    [DataPoints.ProtectionPotionsFrostAbsorbed]: " ",
    [DataPoints.ProtectionPotionsShadow]: " ",
    [DataPoints.ProtectionPotionsGreaterShadow]: " ",
    [DataPoints.ProtectionPotionsMajorShadow]: " ",
    [DataPoints.ProtectionPotionsShadowAbsorbed]: " ",
    [DataPoints.ProtectionPotionsGreaterArcane]: " ",
    [DataPoints.ProtectionPotionsMajorArcane]: " ",
    [DataPoints.ProtectionPotionsArcaneAbsorbed]: " ",
    [DataPoints.ConsumesPotions]: " ",
    [DataPoints.ConsumesDrums]: " ",
    [DataPoints.ConsumesGems]: " ",
    [DataPoints.ConsumesExplosives]: " ",
    [DataPoints.ConsumesBandages]: " ",
    [DataPoints.ConsumesManaPots]: " ",
    [DataPoints.ConsumesRunes]: " ",
    [DataPoints.ConsumesRejuvPots]: " ",
    [DataPoints.ConsumesHealthPots]: " ",
    [DataPoints.ConsumesHealthStones]: " ",
    [DataPoints.ConsumesRagePotions]: " ",
    [DataPoints.ConsumesThistleTea]: " ",
    [DataPoints.ConsumesRestorationPots]: " ",
    [DataPoints.ConsumesElixirOfPoisonResistance]: " ",
    [DataPoints.ConsumesFreeActionPotion]: " ",
    [DataPoints.ConsumesManaGem]: " ",
    [DataPoints.ConsumesNightmareSeed]: " ",
    [DataPoints.ConsumesStoneshield]: " ",
    [DataPoints.ConsumesOilOfImmolation]: " ",
    [DataPoints.ConsumesHeavyRuneclothBandage]: " ",
    [DataPoints.ConsumesAntiVenom]: " ",
    [DataPoints.ConsumesHolyWater]: " ",
    [DataPoints.ConsumesSapperCharge]: " ",
    [DataPoints.ConsumesEzThro]: " ",
    [DataPoints.ConsumesDenseDynamite]: " ",
    [DataPoints.ConsumesDrumsBattle]: " ",
    [DataPoints.ConsumesDrumsRestoration]: " ",
    [DataPoints.ConsumesDrumsPanic]: " ",
    [DataPoints.ConsumesDrumsWar]: " ",
    [DataPoints.ConsumesInsaneStrength]: " ",
    [DataPoints.ConsumesShrouding]: " ",
    [DataPoints.ConsumesFelRegeneration]: " ",
    [DataPoints.ConsumesHeroic]: " ",
    [DataPoints.ConsumesDestruction]: " ",
    [DataPoints.ConsumesHaste]: " ",
    [DataPoints.ConsumesFelMana]: " ",
    [DataPoints.ConsumesIronshield]: " ",
    [DataPoints.DispelTotal]: " ",
    [DataPoints.DispelBoss]: " ",
    [DataPoints.DispelTrash]: " ",
    [DataPoints.DispelPoison]: " ",
    [DataPoints.DispelDisease]: " ",
    [DataPoints.DispelCurse]: " ",
    [DataPoints.DispelMagic]: " ",
    [DataPoints.DispelFrenzy]: " ",
    [DataPoints.DispelDruidCurePoison]: " ",
    [DataPoints.DispelDruidAbolishPoison]: " ",
    [DataPoints.DispelDruidRemoveCurse]: " ",
    [DataPoints.DispelHunterTranqShot]: " ",
    [DataPoints.DispelMageRemoveLesserCurse]: " ",
    [DataPoints.DispelPaladinPurify]: " ",
    [DataPoints.DispelPaladinCleanse]: " ",
    [DataPoints.DispelPriestDispelMagic]: " ",
    [DataPoints.DispelPriestCureDisease]: " ",
    [DataPoints.DispelPriestAbolishDisease]: " ",
    [DataPoints.DispelShamanPurge]: " ",
    [DataPoints.DispelShamanCurePoison]: " ",
    [DataPoints.DispelShamanCureDisease]: " ",
    [DataPoints.DispelShamanPoisonCleansingTotem]: " ",
    [DataPoints.DispelShamanDiseaseCleansingTotem]: " ",
    [DataPoints.InterruptTotal]: " ",
    [DataPoints.InterruptDruidBash]: " ",
    [DataPoints.InterruptDruidFeralCharge]: " ",
    [DataPoints.InterruptMageCounterspell]: " ",
    [DataPoints.InterruptPaladinHammerOfJustice]: " ",
    [DataPoints.InterruptPriestSilence]: " ",
    [DataPoints.InterruptRogueKick]: " ",
    [DataPoints.InterruptShamanEarthShock]: " ",
    [DataPoints.InterruptWarriorPummel]: " ",
}
